CREATE DATABASE test;

\c test;

CREATE TABLE
    "categories" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "category_name" varchar(50) NOT NULL
    );

CREATE TABLE
    "level" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "lvl_name" varchar(100) NOT NULL
    );

CREATE TABLE
    "roles" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "rol_name" varchar(100) NOT NULL
    );

CREATE TABLE
    "courses_video" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "title" varchar(180) NOT NULL,
        "url" varchar(280) NOT NULL
    );

CREATE TABLE
    "country" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "country_name" varchar(100) NOT NULL
    );

CREATE TABLE
    "users" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" varchar(50) NOT NULL,
        "last_name" varchar(50) NOT NULL,
        "email" varchar(50) NOT NULL,
        "password" varchar(10) NOT NULL,
        "age" int NOT NULL,
        "country_id" int NOT NULL
    );

CREATE TABLE
    "user_rol" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" int NOT NULL,
        "rol_id" int NOT NULL
    );

CREATE TABLE
    "courses" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "title" varchar(100) NOT NULL,
        "description" varchar(180) NOT NULL,
        "id_lvl" INT NOT NULL,
        "id_teacher" INT NOT NULL,
        "id_category" INT NOT NULL
    );

CREATE TABLE
    "course_category" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "course_id" INT NOT NULL,
        "video_id" INT NOT NULL
    );

ALTER TABLE "users"
ADD FOREIGN KEY ("country_id") REFERENCES "country" ("id");

ALTER TABLE "user_rol"
ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_rol"
ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "courses"
ADD FOREIGN KEY ("id_lvl") REFERENCES "level" ("id");

ALTER TABLE "courses"
ADD FOREIGN KEY ("id_category") REFERENCES "categories" ("id");

ALTER TABLE "courses"
ADD FOREIGN KEY ("id_teacher") REFERENCES "user_rol" ("id");

ALTER TABLE "course_category"
ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "course_category"
ADD FOREIGN KEY ("video_id") REFERENCES "courses_video" ("id");


INSERT INTO categories (category_name) VALUES ('Data Scients'), ('Desing');

INSERT INTO level (lvl_name) VALUES ('Begginer'), ('Middle'), ('Advance');

INSERT INTO roles (rol_name) VALUES ('admin'), ('teacher'), ('student');

INSERT INTO courses_video (title, url) VALUES
    ('Intro SQL','www.courses.com/cat?=data-science/vid_intro.mp4'),
    ('UX patterns','www.courses.com/cat?=data-science/vid_figma.mp4');

INSERT INTO country (country_name) VALUES ('Mexico'), ('Colombia'), ('Peru');

INSERT INTO users (name, last_name, email, password, age, country_id) VALUES
    ('Carla', 'Contreras', 'carl.cont@email.com', '1234pass', 27, 1),
    ('Fernando', 'Bustamante', 'BustaFer@gmail.com', '1we4pass', 27, 3);


INSERT INTO user_rol (user_id, rol_id) VALUES (1,2), (2,3);

INSERT INTO courses (title, description, id_lvl, id_teacher, id_category) VALUES
    ('Data Science fot dummys', 'A course with a data science bases', 1, 2, 1),
    ('FIgma Desing', 'A course of figma dor developers', 2, 1, 2);

INSERT INTO course_category (course_id, video_id) VALUES (1, 1), (2,2);